tags:
- name: deck
  description: deck API

paths:
# [GET] Get deck
  /deck:
    get:
      tags:
      - deck
      summary: Get deck
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] Create deck
    post:
      tags:
      - deck
      summary: Create a deck
      parameters:
      - name: body
        in: body
        description: Deck data
        required: true
        schema:
          $ref: '#/definitions/cards'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] Draw cards from deck
  /deck/{deckId}/draw/{count}:
    get:
      tags:
      - deck
      summary: Draw card from deck
      parameters:
      - name: deckId
        in: path
        description: Deck Id
        required: true
      - name: count
        in: path
        description: Number of cards to draw
        required: true
        responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'


schemes:
 - https
 - http
